// ── Training Guide System — Types + Content ─────────────────────────────────

export interface GuideStep {
  title: string;
  subtitle?: string;
  illustration: string[];
  bullets: string[];
  tip?: string;
}

export interface FeatureGuideData {
  id: string;
  title: string;
  subtitle: string;
  agentName: string;
  steps: GuideStep[];
}

// ── GL Design Coach — COA Design Workbench Guide ────────────────────────────

export const GL_DESIGN_COACH_GUIDE: FeatureGuideData = {
  id: "gl-design-coach",
  title: "COA Design Workbench",
  subtitle: "7 tabs, two modes — your complete chart of accounts workspace",
  agentName: "GL Design Coach",
  steps: [
    {
      title: "Overview",
      subtitle: "Your COA design workspace — 7 tabs, two modes",
      illustration: [
        "┌─────────────────────────────────────────┐",
        "│  Agent Summary Banner                   │",
        "│  ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌  │",
        "│                                         │",
        "│  ┌──────┬──────┬────┬─────┃─────┬───┬──┐│",
        "│  │Code  │Acct  │Dim │Deci ┃Acct │Mat│Hi││",
        "│  │Blocks│Grps  │    │sions┃Str  │rix│er││",
        "│  └──────┴──────┴────┴─────┃─────┴───┴──┘│",
        "│   ↑ Editable Tables ↑    ┃ ↑ Visual ↑   │",
        "│                          ┃              │",
        "│  ┌─────────────────────┐  │  ┌────────┐ │",
        "│  │                     │  │  │ Agent  │ │",
        "│  │   Tab Content       │  │  │ Chat   │ │",
        "│  │                     │  │  │ Panel  │ │",
        "│  └─────────────────────┘  │  └────────┘ │",
        "└─────────────────────────────────────────┘",
      ],
      bullets: [
        "The first 4 tabs (Code Blocks → Decisions) are editable data tables — this is where you shape the COA structure. Every cell is click-to-edit.",
        "The last 3 tabs (Account String → Hierarchy) are interactive visualizations — presentation-ready views for CFO decks or design validation.",
        "The agent seeds all 7 tabs from the GL data analysis. You start with a complete draft, not a blank page.",
        "Check the Agent Summary banner at the top — it tells you what the agent found and what needs attention.",
      ],
      tip: "Start with the Decisions tab to see what the agent is unsure about, then work through Code Blocks and Dimensions to refine the structure.",
    },
    {
      title: "Code Blocks",
      subtitle: "Define account number ranges and their purpose",
      illustration: [
        "┌────────────────────────────────────────┐",
        "│ Range     Type         STAT Align  Count│",
        "│ ─────────────────────────────────────── │",
        "│ 400100-   Written      Line 19.1     12 │",
        "│ 400199    Premium      PPA No-Fault     │",
        "│                                         │",
        "│ 400200-   Assumed      Schedule P     4 │",
        "│ 400299    Premium      Part 1           │",
        "│                                         │",
        "│ 500100-   Losses       Lines 1-4     18 │",
        "│ 500199    Incurred                      │",
        "│                                         │",
        "│ 600100-   Investment   Schedule DA    6  │",
        "│ 600199    Income                        │",
        "│ ─────────────────────────────────────── │",
        "│ [ + Add Row ]                           │",
        "└────────────────────────────────────────┘",
      ],
      bullets: [
        "Each row is an account range (e.g. 400100–400199 = Written Premium). Click any cell to edit the range, type, or alignment.",
        "The Statutory Alignment column maps each range to Annual Statement line items. Verify this matches the client's current statutory filing.",
        "Count shows how many accounts the agent found in that range. Zero-count rows may indicate unused ranges you can consolidate.",
        "Click + Add Row for ranges the agent missed — common for new account structures planned for S/4HANA migration.",
      ],
      tip: "Sort mentally by account type (A→L→E→R→X). If you see gaps in the sequence, ask whether the client has ranges planned for future use.",
    },
    {
      title: "Account Groups",
      subtitle: "Roll up accounts into statutory reporting groups",
      illustration: [
        "┌────────────────────────────────────────┐",
        "│ Code  Name          Schedule   Accounts│",
        "│ ──────────────────────────────────────  │",
        "│ NPW   Net Premiums  Pg 4,        14   │",
        "│       Written       Lines 1-21         │",
        "│                                         │",
        "│ NLI   Net Losses    Sch P,        12   │",
        "│       Incurred      Parts 1-3          │",
        "│                                         │",
        "│ LAE   Loss Adj      Sch P,         8   │",
        "│       Expense       Part 3             │",
        "│                                         │",
        "│ UWX   Underwriting  Pg 4,         10   │",
        "│       Expenses      Lines 25-28        │",
        "│ ──────────────────────────────────────  │",
        "│ Notes: [click to add rationale]         │",
        "└────────────────────────────────────────┘",
      ],
      bullets: [
        "Each group has a Schedule Line reference (e.g. \"Line 19.1 — PPA No-Fault\"). Verify these match the client's current annual statement.",
        "Account Count shows how many natural accounts roll into each group. Imbalanced counts (1 vs 50) may signal over- or under-granularity.",
        "Add consultant Notes to document design rationale — these persist and appear in the deliverable export.",
        "Click + Add Row if the client needs groups that don't exist in their legacy COA (common when adding new lines of business).",
      ],
      tip: "Cross-reference these groups with the Dynamic Hierarchy tab (Step 8) — the FSLI tree should mirror your group structure.",
    },
    {
      title: "Dimensions",
      subtitle: "Assess dimension health and flag issues",
      illustration: [
        "┌────────────────────────────────────────┐",
        "│ Dimension    Fill%  Values  Req  Issues│",
        "│ ──────────────────────────────────────  │",
        "│ Company      100%     3     ✓    —     │",
        "│ Department    95%    12     ✓    —     │",
        "│ LOB           88%     8     ✓   2 open │",
        "│ Reinsurance   65%     4     —   1 open │",
        "│ Product       72%    15     —    —     │",
        "│                                         │",
        "│ ┌─ Issue Card ───────────────────────┐  │",
        "│ │ ⚠ Missing LOB on 12% of postings  │  │",
        "│ │ Resolution: ___________________    │  │",
        "│ │ [Start Working] [Resolve] [Defer]  │  │",
        "│ └────────────────────────────────────┘  │",
        "└────────────────────────────────────────┘",
      ],
      bullets: [
        "Fill Rate is your primary quality indicator. 100% = every transaction uses this dimension. Below 80% = investigate why transactions are missing it.",
        "Issues appear inline as amber badges. Click to expand. For each issue: Start Working (claim it), Resolve (add notes), or Defer (document why).",
        "Mandatory toggle marks whether this dimension is required on every GL posting. Toggle based on client requirements and ERP configuration.",
        "Key Values shows the most common values — verify these match the client's master data.",
      ],
      tip: "Focus on dimensions with fill rate below 90% first. Low fill rates often indicate the legacy system allowed optional posting that will be mandatory in S/4HANA.",
    },
    {
      title: "Decisions",
      subtitle: "Approve or reject agent recommendations",
      illustration: [
        "┌────────────────────────────────────────┐",
        "│ ┌─ Decision Card ─────────── PENDING ┐ │",
        "│ │                                     │ │",
        "│ │ GAAP/STAT Alignment Approach        │ │",
        "│ │                                     │ │",
        "│ │ Context:  Current COA uses single   │ │",
        "│ │           hierarchy for both...     │ │",
        "│ │                                     │ │",
        "│ │ Recommend: Separate FSLI trees per  │ │",
        "│ │            reporting framework      │ │",
        "│ │                                     │ │",
        "│ │ Alternative: Unified tree with      │ │",
        "│ │              perspective overlays   │ │",
        "│ │                                     │ │",
        "│ │ Consultant Notes: _______________   │ │",
        "│ │ [✓ Approve]  [✗ Reject]  [Reset]   │ │",
        "│ └─────────────────────────────────────┘ │",
        "└────────────────────────────────────────┘",
      ],
      bullets: [
        "Read the Context (why this matters), Recommendation (agent suggestion), Alternative (what else could work), and Impact (what changes).",
        "Click Approve to accept or Reject to override. Either way, add Consultant Notes explaining your rationale — this is part of the audit trail.",
        "The amber badge count on the Decisions tab shows pending items. Your goal: zero pending decisions before deliverable review.",
        "Rejected decisions stay visible with a red badge so the team can see what was considered and why.",
      ],
      tip: "Tackle high-impact decisions first. If the agent recommended a GAAP/STAT alignment approach, that cascades into hierarchy design — resolve it before the visualization tabs.",
    },
    {
      title: "Account String Diagram",
      subtitle: "Visualize the full GL account string for CFO presentations",
      illustration: [
        "┌────────────────────────────────────────┐",
        "│  Account String Composition             │",
        "│                                         │",
        "│ ┌──────┬──────┬──────────┬────┬──┬────┐ │",
        "│ │      │      │          │    │  │    │ │",
        "│ │ Co   │ Dept │ Natural  │LOB │Re│Prod│ │",
        "│ │ 4chr │ 4chr │ 6chr    │4chr│2 │4chr│ │",
        "│ │      │      │          │    │  │    │ │",
        "│ │ 1000 │CC3000│ 400100  │AUTO│QS│PPA │ │",
        "│ └──────┴──────┴──────────┴────┴──┴────┘ │",
        "│   widths ∝ cardinality                   │",
        "│                                         │",
        "│ Statutory Alignment:                    │",
        "│ [19.1 PPA] [19.2 Liab] [4 Home] [5.1]  │",
        "└────────────────────────────────────────┘",
      ],
      bullets: [
        "Each colored block is a segment (Company, Department, Natural Account, etc.). Widths are proportional to unique value counts.",
        "Click any segment to see its detail card: character length, unique values, fill rate, and statutory alignment.",
        "The Statutory Alignment Summary pills show which annual statement lines your COA covers. Gaps = statutory reporting risk.",
        "This view is screenshot-ready for executive decks. It answers: \"Show me the full account string with all segments.\"",
      ],
      tip: "If Natural Account is disproportionately wide (high cardinality), the client may have too many natural accounts — an opportunity to consolidate during migration.",
    },
    {
      title: "Dimensional Matrix",
      subtitle: "Find gaps and validate coverage across dimensions",
      illustration: [
        "┌────────────────────────────────────────┐",
        "│         AUTO  HOME  COMML  WC  (none)  │",
        "│ ──────────────────────────────────────  │",
        "│ Assets   ██    ██    ██    ██    ██    │",
        "│ Liabs    ██    ██    ██    ██    ██    │",
        "│ Equity   ░░    ░░    ░░    ░░    ██    │",
        "│ Revenue  ██    ██    ██    ██    ░░    │",
        "│ Expense  ██    ██    ██    ██    ██    │",
        "│                                         │",
        "│ ██ = active  ░░ = unused                │",
        "│                                         │",
        "│ Coverage: 21/25 (84%)                   │",
        "│ Unused: 4 combinations                  │",
        "│ ──────────────────────────────────────  │",
        "│ Click any cell for drill-down            │",
        "└────────────────────────────────────────┘",
      ],
      bullets: [
        "Green cells = active combinations with GL activity. Gray cells = no accounts in that intersection.",
        "Click any cell to drill down: account count, posting count, dollar volume, and reinsurance breakdown.",
        "Use the Reinsurance dropdown to toggle an overlay showing how QS, XOL, and Facultative distribute across the matrix.",
        "The Rationalization Insights section flags unused combinations that can be eliminated and expected gaps (like Equity × LOB).",
      ],
      tip: "The unused combination count is your simplification KPI. In most P&C carriers, 30–40% of theoretical combinations are unused. Higher = over-engineered COA.",
    },
    {
      title: "Dynamic Hierarchy",
      subtitle: "Classify accounts into FSLI reporting structure across perspectives",
      illustration: [
        "┌────────────────────────────────────────┐",
        "│                     [STAT] [GAAP] [I17]│",
        "│ ┌─ FSLI Tree ───┐ ┌─ Accounts ──────┐ │",
        "│ │ Net Prem (14)  │ │                  │ │",
        "│ │  ├ Direct (8)  │ │ Tier 1 — Rule    │ │",
        "│ │  ├ Assumed (2) │ │ ██ 400100 WP Dir │ │",
        "│ │  └ Ceded (4)   │ │ ██ 400110 WP Dir │ │",
        "│ │ Net Losses(12) │ │                  │ │",
        "│ │ LAE (8)        │ │ Tier 2 — Pattern │ │",
        "│ │ UW Exp (10)    │ │ ▓▓ 500750 Alloc  │ │",
        "│ │ Inv Inc (6)    │ │                  │ │",
        "│ │ Other (4)      │ │ Tier 3 — Agent   │ │",
        "│ └────────────────┘ │ ░░ 700100 Misc ⚠ │ │",
        "│                    │  [Approve][Reject]│ │",
        "│                    └──────────────────┘ │",
        "│ ┌─ Audit Card ──────────────────────┐   │",
        "│ │ 700100 — Basis · Agent · Hash     │   │",
        "│ └───────────────────────────────────┘   │",
        "└────────────────────────────────────────┘",
      ],
      bullets: [
        "Tier 1 (Rule, emerald): Deterministic range-based classification — high confidence, no review needed.",
        "Tier 2 (Pattern, blue): Name/type heuristic matches — medium confidence, spot-check a few.",
        "Tier 3 (Agent, amber): LLM reasoning where no rule or pattern matched — requires your approval. Click Approve or Reject inline.",
        "Switch between STAT / GAAP / IFRS 17 perspectives using the toggle buttons. Each shows a different FSLI tree for the same accounts.",
        "Click any account to see its Audit Card: classification basis, agent, confidence, content hash, and full change history.",
      ],
      tip: "Focus review time on Tier 3 accounts — the agent is explicitly asking for your expert judgment. Tier 1 and 2 are pre-validated, but you can still override them (logged in audit trail).",
    },
  ],
};

// ── Guide Registry ──────────────────────────────────────────────────────────

export const GUIDE_REGISTRY: Record<string, FeatureGuideData> = {
  gl_design_coach: GL_DESIGN_COACH_GUIDE,
};
